 <header>
   <nav class="navbar navbar-expand-lg bg-body-tertiary">
     <div class="container-fluid">
       <img class="logocabecalho" src="/imagens/Max faxinas.png" alt="Logo Max Faxinas">
       <!--    <a class="navbar-brand" href="#">Navbar</a> -->
       <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
         aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
       </button>
       <div class="collapse navbar-collapse" id="navbarNavDropdown">
         <ul class="navbar-nav">
           <li class="nav-item">
             <a class="nav-link" aria-current="page" href="home">Home</a>
           </li>
           <li class="nav-item">
             <a class="nav-link" href="quemsou">Quem sou</a>
           </li>
           <li class="nav-item">
             <a class="nav-link" href="servico">Serviços</a>
           </li>
            <li class="nav-item">
             <a class="nav-link" href="adicional">Adicional</a>
           </li>
         </ul>
         <ul class="navbar-nav ms-auto">
           <li class="nav-item">
             <a class="nav-link btn" href="">
               <i class="bi bi-bag"></i>
             </a>
           </li>

           <li class="nav-item">
             <div class="dropdown">
               <a class="btn" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                 <i class="bi bi-person-circle"></i>
               </a>

               <ul class="dropdown-menu dropdown-menu-end">
                 <li>
                   <a class="dropdown-item" href="perfil">Ver perfil</a>
                 </li>
                 <li>
                   <a class="dropdown-item bntSair" href="/sair">
                     <i class="bi bi-x-circle me-2"></i>Sair</a>
                 </li>
               </ul>
             </div>
           </li>

         </ul>

       </div>
     </div>
   </nav>
 </header>