<h1>Área do Administrador</h1>
<h3>Lista de Agendamentos</h3>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Data</th>
      <th scope="col">Status</th>
      <th scope="col">Cliente</th>
      <th scope="col">Serviço</th>
    </tr>
  </thead>
  <tbody>
    <?php if (!empty($agendamentos)): ?>
      <?php foreach ($agendamentos as $agendamento): ?>
        <tr>
          <td><?= $agendamento->getId() ?></td>
          <td><?= $agendamento->getData() ?></td>
          <td><?= $agendamento->getStatus() ?></td>
          <td><?= $agendamento->getCliente()->getNome() ?></td>
          <td><?= $agendamento->getServico()->getNome() ?></td>
        </tr>
      <?php endforeach ?>
    <?php else: ?>
        <p>Nenhum agendamento encontrado</p>
    <?php endif; ?>
  </tbody>
</table>