<?php
$agendamentos = [];
?>
<h1>Área do Administrador</h1>
<h3>Lista de Usuários</h3>
<table>
    <tr>
        <th>Id</th>
        <th>CPF</th>
        <th>Nome</th>
        <th>Email</th>
        <th>Telefone</th>
        <th>Endereço</th>
    </tr>
    <?php foreach ($agendamentos as $agedamento): ?>
        <tr>
            <td><?= $agedamento->getId() ?></td>
            <td><?= $agedamento->getCpf() ?></td>
            <td><?= $agedamento->getNome() ?></td>
            <td><?= $agedamento->getEmail() ?></td>
            <td><?= $agedamento->getTelefone() ?></td>
            <td><?= $agedamento->getEndereco() ?></td>

        </tr>
    <?php endforeach ?>
</table>

