<main>
  <section class="agendamento">
    <h1 class="titulo mb-4">Finalizar Agendamento</h1>

    <div class="card p-3 mb-2">
      <h4 class="mb-3">Serviço selecionado:</h4>
      <ul class="list-unstyled">
        <?php foreach ($carrinho as $item): ?>
          <li><?= $item["nome_servico"] ?> - R$<?= number_format($item["valor_servico"], 2, ",", ".")  ?></li>
          <li>Data: <?= $item["data"] ?></li>
          <?php if (!empty($item["adicionais"])): ?>
            <li class="mt-2"><strong>Adicionais:</strong>
              <ul class="list-unstyled">
                <?php foreach ($item["adicionais"] as $ads): ?>
                  <li><?= $ads["nome"] ?> - R$<?= number_format($ads["preco"], 2, ",", ".") ?></li>
                <?php endforeach; ?>
                <br>
                <li>Valor total: R$<?= number_format($item["valor_total"], 2, ",", ".") ?></li>

              </ul>
            </li>
          <?php endif; ?>
        <?php endforeach; ?>
      </ul>


      <form id="form" method="POST" action="/enviar">

        <div class="mb-3">
          <h4>Endereço:</h4>
          <?php if (!empty($enderecos)): ?>
            <?php foreach ($enderecos as $endereco): ?>
              <div class="form-check">
                <input type="radio" class="form-check-input" name="user_endereco" value="<?= $endereco->getId() ?>">
                <label class="form-check-label">
                  <?= $endereco->getRua() ?>, <?= $endereco->getNumero() ?> - <?= $endereco->getBairro() ?>
                </label>
              </div>
            <?php endforeach; ?>
          <?php else: ?>
            <p>Nenhum serviço encontrado</p>
          <?php endif; ?>
        </div>

        <h4>Forma de pagamento</h4>
        <select name="formaPagamento" id="formaPagemento" class="form-select">
          <option value="">Selecione uma forma de pagamento</option>
          <?php foreach ($formasPagamento as $fp): ?>
            <option value="<?= $fp->getId() ?>">
              <?= $fp->getTipo() ?>
            </option>
          <?php endforeach; ?>
        </select>
        <div id="pagamento-info" class="mt-3"></div>
        <div class="col-12">
          <button class="btn btn-agendamento" type="submit">Enviar</button>
        </div>

      </form>
    </div>
  </section>

</main>