<main >
    <section class="agendamento backgroundLogin">
    <form>
        <div class="card">
            <div class="card-header">
                <h2 class="titulo">Cadastro</h2>
            </div>
            <div class="card-body">
                <label for="email">Digite seu e-mail</label>
                <input type="text">

                <label for="senha">Digite sua senha</label>
                <input type="text">

            </div>
        </div>
    </form>
     </section>
</main>