<main>
    <section class="agendamento backgroundLogin">
        <div class="card">
            <div class="card-header">
                <h2 class="titulo">Cadastro</h2>
            </div>
            <div class="card-body form-cadastro">
                <form id="form" method="post" action="/cadastrar" class="row g-3 formCadastro">
                    <div class="mb-3">
                        <label for="name" class="form-label">Nome:</label>
                        <input type="text" id="name" class="form-control" placeholder="Digite seu nome completo" name="user_nome">
                        <div id="erroNome" class="erro-message"></div>
                    </div>

                    <div class="mb-3 col-md-6">
                        <label for="name" class="form-label">CPF:</label>
                        <input type="text" id="cpf" class="form-control cpf" placeholder="Digite seu CPF" name="user_cpf">
                        <div id="erroCpf" class="erro-message"></div>
                    </div>
                    <div class="mb-3 col-md-6">
                        <label for="telefone" class="form-label">Telefone:</label>
                        <input type="tel" id="telefone" class="form-control telefone" placeholder="(XX) XXXXX-XXXX" name="user_telefone">
                        <div id="erroTelefone" class="erro-message"></div>
                    </div>

                    <div class="mb-3 col-md-4">
                        <label class="form-label">Cidade:</label>
                        <select name="cidade" id="cidade" class="form-select">
                            <option value="">Selecione uma cidade</option>
                            <?php foreach ($cidades as $c): ?>
                                <option value="<?= $c->getId() ?>">
                                    <?= $c->getNome() ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                        <div id="erroCidade" class="erro-message"></div>
                    </div>

                    <div class="mb-3 col-md-4">
                        <label for="estado" class="form-label">Estado:</label>
                        <input type="text" id="estado" class="form-control" placeholder="Digite seu estado" name="user_estado">
                        <div id="erroEstado" class="erro-message"></div>
                    </div>

                    <div class="mb-3 col-md-4">
                        <label for="pais" class="form-label">País:</label>
                        <input type="text" id="pais" class="form-control" placeholder="Digite seu país" name="user_pais">
                        <div id="erroPais" class="erro-message"></div>
                    </div>


                    <div class="mb-3 col-md-4">
                        <label for="rua" class="form-label">Rua:</label>
                        <input type="text" id="rua" class="form-control" placeholder="Digite o nome da sua rua" name="user_rua">
                        <div id="erroRua" class="erro-message"></div>
                    </div>

                    <div class="mb-3 col-md-4">
                        <label for="numero" class="form-label">Número:</label>
                        <input type="text" id="numero" class="form-control" placeholder="Digite o seu número" name="user_numero">
                        <div id="erroNumero" class="erro-message"></div>
                    </div>

                    <div class="mb-3 col-md-4">
                        <label for="bairro" class="form-label">Bairro:</label>
                        <input type="text" id="bairro" class="form-control" placeholder="Digite o seu bairro" name="user_bairro">
                        <div id="erroBairro" class="erro-message"></div>
                    </div>

                    <div class="mb-3 col-md-6">
                        <label for="email" class="form-label">E-mail:</label>
                        <input type="email" id="email" class="form-control" placeholder="Digite seu e-mail" name="user_email">
                        <div id="erroEmail" class="erro-message"></div>
                    </div>

                    <div class="mb-3 col-md-6">
                        <label for="senha" class="form-label">Defina sua senha:</label>
                        <div class="input-group senhaLogin">
                            <input type="password" name="user_senha" id="senha" class="form-control" placeholder="Digite sua senha">
                            <span type="button" class="btn" onclick="mostrarSenha()">
                                <i class="bi bi-eye"></i>
                            </span>
                        </div>
                        <div id="erroSenha" class="erro-message"></div>
                    </div>
                    <button type="submit" class="btn btn-primary">Cadastrar</button>
                </form>
                <a class="linkCadastro" href="login">Voltar ao login</a>

            </div>
        </div>
    </section>
</main>