<main>
    <section class="agendamento backgroundLogin">
        <div class="card">
            <div class="card-header">
                <h2 class="titulo">Cadastro</h2>
            </div>
            <div class="card-body">
                <form id="form" method="post" action="/cadastrar" class="row g-3">
                    <div class="mb-3">
                        <label for="name" class="form-label">Nome:</label>
                        <input type="text" id="name" class="form-control" placeholder="Digite seu nome completo" name="user_nome">
                    </div>

                    <div class="mb-3 col-md-6">
                        <label for="name" class="form-label">CPF:</label>
                        <input type="text" id="cpf" class="form-control cpf" placeholder="Digite seu CPF" name="user_cpf">
                    </div>

                    <div class="mb-3 col-md-6">
                        <label for="telefone" class="form-label">Telefone:</label>
                        <input type="tel" id="telefone" class="form-control telefone" placeholder="(XX) XXXXX-XXXX" name="user_telefone">
                    </div>

                    <div class="mb-3">
                        <label for="cep" class="form-label">Endereço:</label> <!-- Arrumar o campo do endereço -->
                        <input type="text" id="endereco" class="form-control" placeholder="Digite seu endereço completo: Rua Flores, 1021, Bairro Solar" name="user_endereco">
                    </div>

                    <div class="mb-3">
                        <label for="email" class="form-label">E-mail:</label>
                        <input type="email" id="email" class="form-control" placeholder="Digite seu e-mail" name="user_email">
                    </div>
                    
                        <label for="senha" class="form-label">Defina sua senha:</label>
                        <div class="input-group senhaLogin">
                            <input type="password" name="user_senha" id="senha" class="form-control">
                            <span type="button" class="btn" onclick="mostrarSenha()">
                                <i class="bi bi-eye"></i>
                            </span>
                        </div>
                    
                    <button type="submit" class="btn btn-primary">Cadastrar</button>
                </form>
                <a class="linkCadastro" href="login">Voltar ao login</a>

            </div>
        </div>
    </section>
</main>