<main>
    <section class="agendamento backgroundLogin">
        <div class="card">
            <div class="card-header">
                <h2 class="titulo">Login</h2>
            </div>
            <div class="card-body">
                <form name="form1" method="post" class="formLogin">
                    <label for="email" class="form-label">Digite seu e-mail:</label>
                    <input type="email" name="email" id="email" class="form-control">

                    <label for="senha" class="form-label">Digite sua senha:</label>
                    <div class="input-group senhaLogin">
                        <input type="password" name="user_senha" id="senha" class="form-control">
                        <span type="button" class="btn" onclick="mostrarSenha()">
                            <i class="bi bi-eye"></i>
                        </span>
                    </div>

                    <button type="submit" class="btn btnLogin">
                        Fazer Login
                    </button>
                </form>
                <a class="linkCadastro" href="cadastro">Não tem uma conta? Cadastre-se</a>
            </div>
        </div>
    </section>
</main>